const { he, en, heN, enN, fn, fnk, ref, p, pi, pn, quote, h1, h2, h3, bib, bibEn } = require('./lib');
const { docx } = require('./lib');
const { Paragraph, TextRun, AlignmentType, HeadingLevel } = docx;

// ================= סיכום ומסקנות =================
const conclusion = [
  h1('סיכום ומסקנות'),
  pn(
    he('לשאלת המחקר הראשונה', { bold: true }),
    ' (כלי ההכרעה בהיעדר רישום) העלה העיון ארגז כלים עשיר אך מדורג: הזכות שביושר מכוח הלכת ',
    he('אהרונוב', { bold: true }),
    ' היא עמוד השדרה, המקנה למחזיק הבלתי רשום מעמד מהותי מוגן; ייפוי הכוח הבלתי חוזר הוכר הן כמסמך הממלא את דרישת הכתב הן כוויתור על זכות החזרה ממתנה; עקרון תום הלב ו"זעקת ההגינות" משמשים שסתום למקרי הקיצון שבהם אין כל מסמך; והרישיון במקרקעין מגן על מי שהחזיק בהסכמה בלא עסקה. ואולם, כפי שהראה פרק ז, זהו מענה שיפוטי בדיעבד: הוא מציל את המקרה הקונקרטי ואינו מרפא את הכשל המבני.'
  ),
  pi(
    he('לשאלת המחקר השנייה', { bold: true }),
    ' (התניית הרישום במס) נמצא כי הצימוד שבין המרשם לרשות המסים פועל על עסקאות היסטוריות כחסם מצטבר: חוב השבח, הרכישה, ההצמדה, הריבית והקנסות של עסקת שנות השבעים מוטל כתנאי סף על הדור המבקש להסדיר היום. במישור האזרחי אין באי הדיווח כדי לאיין את העסקה, אך במישור המעשי הוא מקים "מעגל אי רישום" המזין את עצמו ומחולל סכסוכים. הניסיון המצרי, שבו הוליד צימוד דומה אי רישום של למעלה מתשעים אחוזים עד שנותק ברפורמת 2022, מלמד כי מדובר בכשל מדיניות מבני ולא בכשל אכיפה.'
  ),
  pi(
    he('לשאלת המחקר השלישית', { bold: true }),
    ' (משקלם של היתר הבנייה והארנונה) הוצע בפרק ד מדרג: אלה אינן ראיות בעלות, שכן מוסדות התכנון והגבייה אינם מכריעים בקניין והארנונה נגבית מן המחזיק באשר הוא; אך הן ראיות נסיבתיות רבות ערך להחזקה, להשקעה ולהסכמה המשפחתית שבזמן אמת. כוחן במצטבר ובקוהרנטיות שלהן עם יתר הראיות, לא כתחליף רישום.'
  ),
  pi(
    he('במישור ההשוואתי', { bold: true }),
    ' חשפה העבודה רצף גנאלוגי אחד: מן הקַבְּץ׳ והחִיאזָה השרעיים, דרך המג׳לה וחוק הקרקעות העות׳מאני, אל ייפוי הכוח הבלתי חוזר של הפרקטיקה הערבית ואל הזכות שביושר שמקורה אנגלי. הסכסוך הפנים משפחתי על מקרקעין לא רשומים איננו "סטייה" מקומית מן הדין, אלא מפגש בין שלוש תפיסות הקניה החיות בשכבות השיטה: תפיסה פיזית, מסמך פרטי ומרשם ממלכתי; והשופט הישראלי המכריע בתיק כזה מיישב, בלא דעת, בין המג׳לה לבין חוק המקרקעין.'
  ),
  pi(
    'המסקנה המרכזית העולה מן המכלול היא שנקודת הכובד של הטיפול בתופעה חייבת לנוע מן ההכרעה השיפוטית בדיעבד אל הסרת החסמים מראש: הסדרה פיסקלית מקילה לעסקאות היסטוריות, השלמת הליכי ההסדר בשיתוף הקהילות, ומסגור דוקטרינרי יציב של ההגנה על המסתמך. נותרות פתוחות שאלות הראויות למחקר המשך, ובהן היקפה האמפירי של התופעה ומעמדן של נשים בהסדרים הפנים משפחתיים הנדונים. המרשם הוא משאת הנפש; אך עד שיגיעו אליו כל בתי החברה הערבית, מוטב שהדרך אליו תהיה גשר, ולא חומה.'
  ),
];

// ================= ביבליוגרפיה =================
function bibTitle(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    bidirectional: true,
    spacing: { before: 240, after: 160 },
    children: [new TextRun({ text, rightToLeft: true, bold: true, size: 28, font: 'David', color: '000000' })],
  });
}

const bibliography = [
  h1('ביבליוגרפיה'),

  bibTitle('חקיקה ישראלית'),
  bib('חוק המקרקעין, התשכ"ט–1969.'),
  bib('חוק המתנה, התשכ"ח–1968.'),
  bib('חוק השליחות, התשכ"ה–1965.'),
  bib('חוק הירושה, התשכ"ה–1965.'),
  bib('חוק מיסוי מקרקעין (שבח ורכישה), התשכ"ג–1963.'),
  bib('חוק ההתיישנות, התשי"ח–1958.'),
  bib('חוק לביטול המג׳לה, התשמ"ד–1984.'),
  bib('פקודת הסדר זכויות במקרקעין [נוסח חדש], התשכ"ט–1969.'),
  bib('פקודת הראיות [נוסח חדש], התשל"א–1971.'),
  bib('חוק התכנון והבנייה, התשכ"ה–1965.'),
  bib('פקודת העיריות [נוסח חדש].'),
  bib('תקנות התכנון והבניה (רישוי בניה), התשע"ו–2016.'),
  bib('חוק הקרקעות העות׳מאני, 1858.'),
  bib('מג׳לת אל-אחכאם אל-עדליה (המג׳לה), 1869–1876.'),

  bibTitle('פסיקה ישראלית'),
  bib('ע"פ 114/63 ', he('קר נ׳ היועץ המשפטי לממשלה', { bold: true }), ', פ"ד יח(3) 561 (1964).'),
  bib('ע"א 516/65 ', he('ריעס נ׳ פורר', { bold: true }), ', פ"ד כ(3) 488 (1966).'),
  bib('בר"ע 178/70 ', he('בוקר נ׳ חברה אנגלו-ישראלית לניהול ואחריות בע"מ', { bold: true }), ', פ"ד כה(2) 121 (1971).'),
  bib('ע"א 726/71 ', he('גרוסמן את ק.ב.ק. בע"מ נ׳ מנהלי עזבון בידרמן', { bold: true }), ', פ"ד כו(2) 781 (1972).'),
  bib('ע"א 649/73 ', he('קפולסקי נ׳ גני גולן בע"מ', { bold: true }), ', פ"ד כח(2) 291 (1974).'),
  bib('ע"א 515/76 ', he('לוי נ׳ ויימן', { bold: true }), ', פ"ד לא(2) 127 (1977).'),
  bib('ע"א 514/76 ', he('חשש נ׳ דמארי', { bold: true }), ', פ"ד לא(2) 505 (1977).'),
  bib('ע"א 32/77 ', he('טבוליצקי נ׳ בית-כנסת ובית-מדרש החסידים', { bold: true }), ', פ"ד לא(3) 210 (1977).'),
  bib('ע"א 463/79 ', he('ג׳בראן נ׳ ג׳בראן', { bold: true }), ', פ"ד לו(4) 403 (1982).'),
  bib('ע"א 496/82 ', he('רוזן נ׳ סלונים', { bold: true }), ', פ"ד לט(2) 337 (1985).'),
  bib('ע"א 986/93 ', he('קלמר נ׳ גיא', { bold: true }), ', פ"ד נ(1) 185 (1996).'),
  bib('ע"א 189/95 ', he('בנק אוצר החייל בע"מ נ׳ אהרונוב', { bold: true }), ', פ"ד נג(4) 199 (1999).'),
  bib('ע"א 1516/99 ', he('לוי נ׳ חיג׳אזי', { bold: true }), ', פ"ד נה(4) 730 (2001).'),
  bib('ע"א 3205/00 ', he('נאטור נ׳ יאסין', { bold: true }), ', פ"ד נה(4) 145 (2001).'),
  bib('ע"א 3911/01 ', he('כספי נ׳ נס', { bold: true }), ', פ"ד נו(6) 752 (2002).'),
  bib('רע"א 1156/02 ', he('חיר נ׳ לידאי', { bold: true }), ', פ"ד נז(3) 949 (2003).'),
  bib('ע"א 1559/99 ', he('צימבלר נ׳ תורג׳מן', { bold: true }), ', פ"ד נז(5) 49 (2003).'),
  bib('ע"א 7139/99 ', he('אלוני נ׳ ארד', { bold: true }), ', פ"ד נח(4) 27 (2004).'),
  bib('ע"א 8234/09 ', he('שם טוב נ׳ פרץ', { bold: true }), ' (נבו 21.3.2011).'),
  bib('ע"א 2110/09 ', he('קדור נ׳ דקסה', { bold: true }), ' (נבו 20.9.2012).'),
  bib('ע"א 6766/11 ', he('חג׳אזי נ׳ חג׳אזי', { bold: true }), ' (נבו 23.6.2013).'),
  bib('ע"א 6588/12 ', he('כבהה נ׳ כבהה', { bold: true }), ' (נבו 24.12.2014).'),
  bib('רע"א 7060/12 ', he('מדינת ישראל נ׳ ', { bold: true }), en('United Israel Appeal Inc', { bold: true }), ' (נבו 30.4.2015).'),
  bib('ע"א 6757/13 ', he('נחום נ׳ רשות הפיתוח', { bold: true }), ' (נבו 19.8.2015).'),
  bib('רע"א 4890/15 ', he('אלוש נ׳ עיריית טבריה', { bold: true }), ' (נבו 31.12.2015).'),
  bib('ו"ע (מחוזי חי׳) 4631-12-13 ', he('גולדברג נ׳ מנהל מיסוי מקרקעין – חדרה', { bold: true }), ', ', he('מיסים', { bold: true }), ' כט/3 ה-320 (2015).'),
  bib('ע"א 483/16 ', he('יהודאי נ׳ חלמיש – חברה ממשלתית-עירונית לדיור, לשיקום ולהתחדשות שכונות בתל-אביב בע"מ', { bold: true }), ' (נבו 3.10.2017).'),
  bib('בע"מ 7496/19 ', he('פלוני נ׳ פלוני', { bold: true }), ' (נבו 30.12.2019).'),
  bib('ע"א 749/18 ', he('עיזבון אבו ג׳נימה נ׳ עיזבון אבו ג׳נימה', { bold: true }), ' (נבו 26.7.2020).'),
  bib('ע"א 3274/18 ', he('אבו אסמעיל נ׳ סלימאן', { bold: true }), ' (נבו 28.7.2020).'),
  bib('ה"פ (מחוזי י-ם) 48783-04-18 ', he('הוך נ׳ בריכטא', { bold: true }), ' (נבו 4.5.2020).'),
  bib('ע"א 4116/20 ', he('הוך נ׳ בריכטא', { bold: true }), ' (נבו 17.9.2020) (החלטה).'),
  bib('ע"א 2693/19 ', he('משעל נ׳ כמאל', { bold: true }), ' (נבו 22.9.2020).'),
  bib('בע"מ 2311/22 ', he('פלוני נ׳ פלוני', { bold: true }), ' (נבו 13.4.2022).'),
  bib('ת"א (מחוזי חי׳) 64669-10-18 ', he('בדארנה נ׳ בדארנה', { bold: true }), ' (נבו 9.1.2022).'),
  bib('עמ"ש (מחוזי מר׳) 52601-10-23 ', he('א.א. נ׳ אר.א', { bold: true }), ' (נבו 1.11.2024).'),
  bib('ת"א (שלום נצ׳) 19781-06-18 ', he('אבו ליל נ׳ פאהום', { bold: true }), ' (נבו 18.10.2023).'),
  bib('תמ"ש (משפחה ת"א) 18541-01-22 ', he('פלונים נ׳ אלמונים', { bold: true }), ' (נבו 15.1.2023).'),
  bib('תלה"מ (משפחה נצ׳) 60777-07-20 ', he('ג.ס נ׳ מ.ד', { bold: true }), ' (נבו 14.4.2021).'),
  bib('תמ"ש (משפחה נצ׳) 4821-07 ', he('ס.ע.ז נ׳ ע.ע.ז', { bold: true }), ' (נבו 2012).'),
  bib('תמ"ש (משפחה נצ׳) 27669-01-17 ', he('ו.ע נ׳ כ.ע', { bold: true }), ' (נבו 22.4.2018).'),
  bib('תלה"מ (משפחה נצ׳) 39735-12-19 ', he('פלונית נ׳ פלוני', { bold: true }), ' (נבו 14.10.2022).'),
  bib('תמ"ש (משפחה חד׳) 44358-11-19 ', he('אלמונית נ׳ פלונית', { bold: true }), ' (נבו 7.5.2023).'),
  bib('ת"א (מחוזי חי׳) 41898-04-18 ', he('שחוק נ׳ עיזבון המנוח שחוק ז"ל', { bold: true }), ' (נבו 21.2.2021).'),
  bib('תמ"ש (משפחה נצ׳) 59099-02-24 ', he('א.ז נ׳ מ.ז', { bold: true }), ' (נבו 10.3.2026).'),

  bibTitle('ספרות עברית'),
  bib('דוד בר-אופיר ', he('הוצאה לפועל – הליכים והלכות', { bold: true }), ' (מהדורה שביעית 2018).'),
  bib('אהרן ברק ', he('חוק השליחות', { bold: true }), ' (מהדורה שנייה 1996).'),
  bib('אבי גורמן ושי אהרונוביץ׳ ', he('מיסוי מקרקעין – פרשנות, הלכה ומעשה', { bold: true }), ' (2017).'),
  bib('טל חבקין ', he('התיישנות', { bold: true }), ' (מהדורה שנייה 2021).'),
  bib('יהושע ויסמן ', he('דיני קניין – חלק כללי', { bold: true }), ' (1993).'),
  bib('יהושע ויסמן "יפוי-כוח בלתי-חוזר כתחליף לבעלות" ', he('משפטים', { bold: true }), ' יד 572 (התשמ"ה).'),
  bib('נינה זלצמן "רישיון במקרקעין" ', he('הפרקליט', { bold: true }), ' מב 24 (התשנ"ה).'),
  bib('"חוזים על פי דיני התורה" ', he('כתר', { bold: true }), ' א 71 (התשנ"ו).'),
  bib('מוחמד ח׳לאילה ואחמד בדראן ', he('שנתון החברה הערבית בישראל 2023', { bold: true }), ' (2023).'),
  bib('חיים זנדברג ', he('הסדר זכויות במקרקעין בארץ-ישראל ובמדינת ישראל', { bold: true }), ' (התש"ס).'),
  bib('חיים זנדברג "עסקה בזכות אובליגטורית או בזכות במקרקעין? תכלית, לשון ואקטיביזם שיפוטי" ', he('משפטים על אתר', { bold: true }), ' יג 79 (התש"ף).'),
  bib('גד טדסקי "הרשאה בלתי-הדירה לביצוע מתנה לאדם שלישי" ', he('משפטים', { bold: true }), ' יט 205 (התשמ"ט).'),
  bib(`אורן יפתחאל, סנדי קדר ואחמד אמארה "עיון מחדש בהלכת 'הנגב המת': זכויות קניין במרחב הבדווי" `, he('משפט וממשל', { bold: true }), ' יד 7 (2012).'),
  bib('נילי כהן "צורת החוזה" ', he('הפרקליט', { bold: true }), ' לח 383 (התשמ"ט).'),
  bib('רונית לוין-שנור "הפרטה, הפרדה והפליה – זניחת ההליכים של הסדר הזכויות במקרקעין במזרח ירושלים" ', he('עיוני משפט', { bold: true }), ' לד 183 (2011).'),
  bib('קייס נאסר ', he('תהליכי התכנון והעיור ביישובים הערביים בישראל', { bold: true }), ' (רביב שלו עורך 2020).'),
  bib('אהרן נמדר ', he('פגיעה במקרקעין [פיצויים בגין נזקי תכנית]', { bold: true }), ' (התשס"ח).'),
  bib('דניאל פרידמן ונילי כהן ', he('חוזים', { bold: true }), ' כרך א (מהדורה שנייה 2018).'),
  bib('מרדכי אלפרדו ראבילו ', he('חוק המתנה, תשכ"ח–1968', { bold: true }), ' (פירוש לחוקי החוזים מיסודו של ג׳ טדסקי, מהדורה שנייה 1996).'),
  bib('אוריאל רייכמן "הערת האזהרה – מהות, יצירה והגנה כנגד עסקות נוגדות" ', he('עיוני משפט', { bold: true }), ' י 297 (1984).'),
  bib('שי שטרן ', he('קהילות במשפט', { bold: true }), ' (2026).'),
  bib('יעקב שקד ', he('פינוי מקרקעין – הליכים והלכות', { bold: true }), ' (מהדורה שנייה 2024).'),

  bibTitle('חקיקה ופסיקה זרה'),
  bibEn('Land Registration Act 2002, c. 9 (UK).'),
  bibEn('Land Registration Act 1925, c. 21 (UK).'),
  bibEn('Law of Property (Miscellaneous Provisions) Act 1989, c. 34 (UK).'),
  bibEn('Powers of Attorney Act 1971, c. 27 (UK).'),
  bibEn('Lysaght v Edwards (1876) 2 Ch D 499 (Ch).'),
  bibEn('Walsh v Lonsdale (1882) 21 Ch D 9 (CA).'),
  bibEn('Re Rose [1952] Ch 499 (CA).'),
  bibEn('Williams & Glyn’s Bank Ltd v Boland [1981] AC 487 (HL).'),
  bibEn('Pennington v Waine [2002] EWCA Civ 227, [2002] 1 WLR 2075.'),
  bibEn('Stack v Dowden [2007] UKHL 17, [2007] 2 AC 432.'),
  bibEn('Thorner v Major [2009] UKHL 18, [2009] 1 WLR 776.'),
  bibEn('Jones v Kernott [2011] UKSC 53, [2012] 1 AC 776.'),
  bibEn('Guest v Guest [2022] UKSC 27, [2022] 3 WLR 911.'),
  bibEn('The Egyptian Civil Code, Law No. 131 of 1948, arts. 1, 418, 714–715, 934, 968–970.'),
  bibEn('Real Estate Publicity Law No. 114 of 1946 (Egypt), as amended by Law No. 9 of 2022.'),
  bibEn('Real Property Registry Law No. 142 of 1964 (Egypt).'),
  bibEn('Law of Inheritance No. 77 of 1943 (Egypt).'),
  bibEn('Constitution of the Arab Republic of Egypt (2014), art. 2.'),
  bibEn('The Mejelle (Majallat al-Ahkam al-Adliyya, 1869–1876), arts. 833–880, 1449–1530, 1660–1675 (C.R. Tyser et al. trans., 1901).'),
  bibEn('The Ottoman Land Code 1858, arts. 20, 78 (F. Ongley trans., 1892).'),

  bibTitle('ספרות זרה'),
  bibEn('Ahmad Amara, ', en('Dispossession by Law: How the Israeli Judicial System Utilizes Ottoman Land Law to Expel and Dispossess the Bedouins', { italics: true }), ', ', en('Journal of Levantine Studies', { smallCaps: true }), ' (2015).'),
  bibEn('Chris Bevan, ', en('Overriding Interests under the Land Registration Act 2002: Time to Repair the ‘Cracked Mirror’?', { italics: true }), ' [2024] ', en('Conveyancer & Property Lawyer', { smallCaps: true }), ' 123.'),
  bibEn(en('N.J. Coulson, Succession in the Muslim Family', { smallCaps: true }), ' (1971).'),
  bibEn(en('Hernando de Soto, The Mystery of Capital: Why Capitalism Triumphs in the West and Fails Everywhere Else', { smallCaps: true }), ' (2000).'),
  bibEn('Kareem Ibrahim & Deena Khalil, ', en('Land Titling: A Tool, not a Panacea — Insights from Egypt', { italics: true }), ', ', en('Metropolitics', { smallCaps: true }), ' (Dec. 20, 2016), metropolitics.org.'),
  bibEn('Ruth Kark, ', en('Consequences of the Ottoman Land Law: Agrarian and Privatization Processes in Palestine, 1858–1918', { italics: true }), ', in ', en('Societies, Social Inequalities and Marginalization', { smallCaps: true }), ' (R. Chand, E. Nel & S. Pelc eds., 2017).'),
  bibEn('Nasr Kheir & Boris A. Portnov, ', en('Land Market Segmentation Along Ethnic Lines: Four Urban Localities in Israel as a Case Study', { italics: true }), ', 136 ', en('Land Use Policy', { smallCaps: true }), ' art. 106916 (2024).'),
  bibEn('L. Landau, ', en('The Gift Law, 1968', { italics: true }), ', 4 ', en('Israel Law Review', { smallCaps: true }), ' 260 (1969).'),
  bibEn(en('Aharon Layish, Women and Islamic Law in a Non-Muslim State: A Study Based on Decisions of the Shari‘a Courts in Israel', { smallCaps: true }), ' (1975).'),
  bibEn('Y. Linant de Bellefonds, ', en('Hiba', { italics: true }), ', in ', en('The Encyclopaedia of Islam', { smallCaps: true }), ' (2d ed.).'),
  bibEn(en('Annelies Moors, Women, Property and Islam: Palestinian Experiences, 1920–1990', { smallCaps: true }), ' (1995).'),
  bibEn('Amos Nadan, ', en('Colonial Misunderstanding of an Efficient Peasant Institution: Land Settlement and Musha‘ Tenure in Mandate Palestine, 1921–47', { italics: true }), ', 46 ', en('Journal of the Economic and Social History of the Orient', { smallCaps: true }), ' 320 (2003).'),
  bibEn('Siti Norfatirah Abdul Rahmani & Mohd Zamro Muda, ', en('Ownership Status of Hibah Marad al-Mawt: A Study on the Views of Classical and Contemporary Scholars', { italics: true }), ', 34(8) ', en('al-Qanatir: International Journal of Islamic Studies', { smallCaps: true }), ' (2025).'),
  bibEn(en('Joseph Schacht, An Introduction to Islamic Law', { smallCaps: true }), ' (1964).'),
  bibEn('Nadav Shoked, ', en('Who Needs Adverse Possession?', { italics: true }), ', 89 ', en('Fordham Law Review', { smallCaps: true }), ' 2639 (2021).'),
  bibEn('David Sims, ', en('Securing Land Tenure in Egypt: Who Needs Registered Titles?', { italics: true }), ', ', en('Metropolitics', { smallCaps: true }), ' (June 14, 2016), metropolitiques.eu.'),
  bibEn('Brian Sloan, ', en('Proprietary Estoppel in the Supreme Court: Banquo’s Ghost?', { italics: true }), ', (2023) 82 ', en('Cambridge Law Journal', { smallCaps: true }), ' 13.'),
  bibEn(en('Kenneth W. Stein, The Land Question in Palestine, 1917–1939', { smallCaps: true }), ' (1984).'),
  bibEn('Alex Waghorn, ', en('Promises in Equity and at Law: Proprietary Estoppel after Guest v Guest', { italics: true }), ', (2023) 86 ', en('Modern Law Review', { smallCaps: true }), ' 1504.'),
  bibEn(en('Konrad Zweigert & Hein Kötz, An Introduction to Comparative Law', { smallCaps: true }), ' (Tony Weir trans., 3d ed. 1998).'),
  bibEn('AAOIFI, Shari‘ah Standard No. 23: Agency and the Act of an Uncommissioned Agent (Fudooli).'),
  bibEn('Law Commission, ', en('Updating the Land Registration Act 2002', { italics: true }), ' (Law Com. No. 380, 2018).'),
  bibEn(en('More than 90% of Egypt’s Properties Are Unregistered: Justice Minister', { italics: true }), ', ', en('Daily News Egypt', { smallCaps: true }), ' (Feb. 14, 2022), dailynewsegypt.com.'),
  bibEn(en('Real Estate Registration Law Amendments – Development Brief', { italics: true }), ', ', en('The Built Environment Observatory', { smallCaps: true }), ' (May 2021), marsadomran.info.'),
  bibEn('Shalakany Law Office, ', en('New Amendments to Real Estate Registration Law: Accelerated and Streamlined Registration Procedures', { italics: true }), ' (2022), shalakany.com.'),
];

module.exports = { conclusion, bibliography };
