// Full and short footnote forms for every source, keyed by "Surname|Year" as cited in src/*.txt.
// The locator (pages, volume) comes from the citation itself and is appended after the form.
module.exports = {
  'אבינרי|1980': { full: "שלמה אבינרי, **הרעיון הציוני לגווניו: פרקים בתולדות המחשבה המדינית היהודית** (תל אביב: עם עובד, 1980)", short: "אבינרי, **הרעיון הציוני לגווניו**" },
  'אבינרי|2007': { full: "שלמה אבינרי, **הרצל** (ירושלים: מרכז זלמן שזר, 2007)", short: "אבינרי, **הרצל**" },
  'אטינגר|1978': { full: "שמואל אטינגר, **האנטישמיות בעת החדשה: פרקי מחקר ועיון** (תל אביב: מורשת וספרית פועלים, 1978)", short: "אטינגר, **האנטישמיות בעת החדשה**" },
  'אנגל|תש"ף': { full: "דוד אנגל, \"גלגולי המושג 'אנטישמיות' והשימוש בו כקטגוריה כוללת\", בתוך: גיא מירון וסקוט אורי (עורכים), **אנטישמיות בין מושג היסטורי לשיח ציבורי**, ציון פה (תש\"ף)", short: "אנגל, \"גלגולי המושג 'אנטישמיות'\"" },
  'ברזלי|תש"ף': { full: "צפריר ברזלי, \"המושג 'אנטישמיות' כקטגוריה לחקר ההיסטוריה של היהודים בימי הביניים\", בתוך: גיא מירון וסקוט אורי (עורכים), **אנטישמיות בין מושג היסטורי לשיח ציבורי**, ציון פה (תש\"ף)", short: "ברזלי, \"המושג 'אנטישמיות' כקטגוריה\"" },
  'דרימון|1886': { full: "אדואר דרימון, \"צרפת המיוהדת\" (1886), בתוך: **מקראת הקורס האנטישמיות במאה ה-19** (רעננה: האוניברסיטה הפתוחה)", short: "דרימון, \"צרפת המיוהדת\"" },
  'הרצל|1997': { full: "בנימין זאב הרצל, **עניין היהודים: ספרי יומן 1895-1904**, תרגם יוסף ונקרט (ירושלים: מוסד ביאליק, 1997)", short: "הרצל, **עניין היהודים**" },
  'השל|תש"ף': { full: "סוזנה השל, \"לקראת היסטוריוגרפיה ארוטית: חקר הממדים החושיים והרגשיים של האנטישמיות\", בתוך: גיא מירון וסקוט אורי (עורכים), **אנטישמיות בין מושג היסטורי לשיח ציבורי**, ציון פה (תש\"ף)", short: "השל, \"לקראת היסטוריוגרפיה ארוטית\"" },
  'וולקוב|2002': { full: "שולמית וולקוב, **במעגל המכושף: יהודים, אנטישמים וגרמנים אחרים** (תל אביב: עם עובד, 2002)", short: "וולקוב, **במעגל המכושף**" },
  'ויטל|1978': { full: "דוד ויטל, **המהפכה הציונית: ראשית התנועה** (תל אביב: עם עובד, 1978)", short: "ויטל, **המהפכה הציונית**" },
  'כ"ץ|1979': { full: "יעקב כ\"ץ, **שנאת ישראל: משנאת הדת לשלילת הגזע** (תל אביב: עם עובד, 1979)", short: "כ\"ץ, **שנאת ישראל**" },
  'לנג|2014': { full: "יוסף לנג, \"תגובות העיתונות העברית בארץ ישראל על פרשת דרייפוס (1894-1906)\", **קשר** 46 (2014)", short: "לנג, \"תגובות העיתונות העברית\"" },
  'מירון|2022': { full: "גיא מירון, **האנטישמיות במאה ה-19: מדריך למידה** (רעננה: האוניברסיטה הפתוחה, 2022)", short: "מירון, **מדריך למידה**" },
  'סחייק|1997': { full: "שאול סחייק, \"פרשת דרייפוס בעיתונות הערבית\", **מיכאל: מאסף לתולדות היהודים בתפוצות** יד (תשנ\"ז)", short: "סחייק, \"פרשת דרייפוס בעיתונות הערבית\"" },
  'פלדמן|תש"ף': { full: "דיוויד פלדמן, \"אנטישמיות ואסלאמופוביה\", תרגם דורון מגן, בתוך: גיא מירון וסקוט אורי (עורכים), **אנטישמיות בין מושג היסטורי לשיח ציבורי**, ציון פה (תש\"ף)", short: "פלדמן, \"אנטישמיות ואסלאמופוביה\"" },
  'פרידריך|2014': { full: "אגניישקה פרידריך, \"פרשת דרייפוס וכתב העת הוורשאי Rola בין השנים 1894-1906\", **קשר** 46 (2014)", short: "פרידריך, \"פרשת דרייפוס וכתב העת הוורשאי Rola\"" },
  'קוץ|2014': { full: "גדעון קוץ, \"ראשיתה של פרשת דרייפוס בעיתונות העברית והיהודית באירופה: כוחן של אידאולוגיות\", **קשר** 46 (2014)", short: "קוץ, \"ראשיתה של פרשת דרייפוס\"" },
  'Avineri|1999': { full: "Shlomo Avineri, \"Theodor Herzl's Diaries as a Bildungsroman,\" *Jewish Social Studies* 5:3 (1999)", short: "Avineri, \"Herzl's Diaries as a Bildungsroman,\"" },
  'Bein|1941': { full: "Alex Bein, *Theodore Herzl: A Biography*, trans. Maurice Samuel (Philadelphia: Jewish Publication Society, 1941)", short: "Bein, *Theodore Herzl*" },
  'Beller|1991': { full: "Steven Beller, *Herzl* (London: Peter Halban, 1991)", short: "Beller, *Herzl*" },
  'Birnbaum|2003': { full: "Pierre Birnbaum, *The Anti-Semitic Moment: A Tour of France in 1898*, trans. Jane Marie Todd (New York: Hill and Wang, 2003)", short: "Birnbaum, *The Anti-Semitic Moment*" },
  'Bredin|1986': { full: "Jean-Denis Bredin, *The Affair: The Case of Alfred Dreyfus*, trans. Jeffrey Mehlman (New York: George Braziller, 1986)", short: "Bredin, *The Affair*" },
  'Cahm|1996': { full: "Eric Cahm, *The Dreyfus Affair in French Society and Politics* (London: Longman, 1996)", short: "Cahm, *The Dreyfus Affair*" },
  'Elon|1975': { full: "Amos Elon, *Herzl* (New York: Holt, Rinehart and Winston, 1975)", short: "Elon, *Herzl*" },
  'Engel|2009': { full: "David Engel, \"Away from a Definition of Antisemitism: An Essay in the Semantics of Historical Description,\" in Jeremy Cohen and Moshe Rosman (eds.), *Rethinking European Jewish History* (Oxford: Littman Library, 2009)", short: "Engel, \"Away from a Definition of Antisemitism,\"" },
  'Harris|2010': { full: "Ruth Harris, *Dreyfus: Politics, Emotion, and the Scandal of the Century* (New York: Metropolitan Books, 2010)", short: "Harris, *Dreyfus*" },
  'Herzl|1899': { full: "Theodor Herzl, \"Zionism,\" *The North American Review* 169 (July 1899)", short: "Herzl, \"Zionism,\"" },
  'Herzl|1960': { full: "Theodor Herzl, *The Complete Diaries of Theodor Herzl*, ed. Raphael Patai, trans. Harry Zohn (New York: Herzl Press and Thomas Yoseloff, 1960)", short: "Herzl, *Complete Diaries*" },
  'Herzl|1988': { full: "Theodor Herzl, *The Jewish State* (New York: Dover, 1988; first published 1896)", short: "Herzl, *The Jewish State*" },
  'Hyman|1998': { full: "Paula E. Hyman, *The Jews of Modern France* (Berkeley: University of California Press, 1998)", short: "Hyman, *The Jews of Modern France*" },
  'Kornberg|1980': { full: "Jacques Kornberg, \"Theodor Herzl: A Reevaluation,\" *Journal of Modern History* 52 (1980)", short: "Kornberg, \"A Reevaluation,\"" },
  'Kornberg|1993': { full: "Jacques Kornberg, *Theodor Herzl: From Assimilation to Zionism* (Bloomington: Indiana University Press, 1993)", short: "Kornberg, *Theodor Herzl*" },
  'Lazare|1896': { full: "Bernard Lazare, *Une erreur judiciaire: La vérité sur l'affaire Dreyfus* (Brussels: Veuve Monnom, 1896)", short: "Lazare, *Une erreur judiciaire*" },
  'Marrus|1971': { full: "Michael R. Marrus, *The Politics of Assimilation: A Study of the French Jewish Community at the Time of the Dreyfus Affair* (Oxford: Clarendon Press, 1971)", short: "Marrus, *The Politics of Assimilation*" },
  'Pawel|1989': { full: "Ernst Pawel, *The Labyrinth of Exile: A Life of Theodor Herzl* (New York: Farrar, Straus and Giroux, 1989)", short: "Pawel, *The Labyrinth of Exile*" },
  'Penslar|2020': { full: "Derek Penslar, *Theodor Herzl: The Charismatic Leader* (New Haven: Yale University Press, 2020)", short: "Penslar, *Theodor Herzl*" },
  'Pulzer|1988': { full: "Peter Pulzer, *The Rise of Political Anti-Semitism in Germany and Austria*, rev. ed. (Cambridge, MA: Harvard University Press, 1988)", short: "Pulzer, *The Rise of Political Anti-Semitism*" },
  'Schorske|1980': { full: "Carl E. Schorske, *Fin-de-siècle Vienna: Politics and Culture* (New York: Alfred A. Knopf, 1980)", short: "Schorske, *Fin-de-siècle Vienna*" },
  'Stewart|1974': { full: "Desmond Stewart, *Theodor Herzl: Artist and Politician* (London: Hamish Hamilton, 1974)", short: "Stewart, *Theodor Herzl*" },
  'Volkov|1978': { full: "Shulamit Volkov, \"Antisemitism as a Cultural Code: Reflections on the History and Historiography of Antisemitism in Imperial Germany,\" *Leo Baeck Institute Year Book* 23 (1978)", short: "Volkov, \"Antisemitism as a Cultural Code,\"" },
  'Wilson|1982': { full: "Stephen Wilson, *Ideology and Experience: Antisemitism in France at the Time of the Dreyfus Affair* (Rutherford: Fairleigh Dickinson University Press, 1982)", short: "Wilson, *Ideology and Experience*" },
  'Wistrich|1989': { full: "Robert S. Wistrich, *The Jews of Vienna in the Age of Franz Joseph* (Oxford: Oxford University Press, 1989)", short: "Wistrich, *The Jews of Vienna*" },
  'Wistrich|1995': { full: "Robert S. Wistrich, \"Theodor Herzl: Zionist Icon, Myth-Maker, and Social Utopian,\" *Israel Affairs* 1:3 (1995)", short: "Wistrich, \"Theodor Herzl: Zionist Icon,\"" },
  'Zola|1898': { full: "Émile Zola, \"J'accuse...! Lettre au Président de la République,\" *L'Aurore*, 13 January 1898", short: "Zola, \"J'accuse...!\"" },
};
